apiVersion: 1
policies:
    - orgId: 1
      receiver: discord_follow_up
      group_by:
          - grafana_folder
          - alertname
      group_wait: 30s
      group_interval: 5m
      # only repeat alerts every 1 week if not solved in the meantime
      repeat_interval: 1w
      routes:
          - receiver: discord_one_shot
            matchers:
                - policy = one_shot
                - alertname != DatasourceError
          - receiver: discord_follow_up
            matchers:
                - policy != one_shot
                - alertname != DatasourceError
